config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :products

  resources :orders, only: [:index, :update,]

  resources :order_products, only: [:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def self.from_order_of(user)
    cart = user.orders.find_by(status: 'open')
  end
end

#OrderProduct.from_order_of(current_user)

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :orders, dependent: :nullify

  GENDER = ["feminine", "masculine"]
  SIZE = ["L", "XL", "XXL", "XXXL"]
  CATEGORY = ["shirts", "pants", "dresses", "skirts", "shoes", "jackets"]

  include PgSearch::Model
  pg_search_scope :product_search,
    against: [ :name, :brand ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  validates :name, :photo, :gender, :size, :category, :price, presence: true
  validates :gender, inclusion: { in: GENDER }
  validates :size, inclusion: { in: SIZE }
  validates :category, inclusion: { in: CATEGORY }

  def is_it_in_the_shopping_cart?(user)
    cart = user.orders.find_by(status: false)

    if cart
      OrderProduct.find_by(order: cart, product: self).present?
    else
      false
    end
  end

  def cart_product(user)
    cart = user.orders.find_by(status: false)

    if cart
      OrderProduct.find_by(order: cart, product: self)
    else
      nil
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :orders, dependent: :nullify

  validates :first_name, :last_name, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  def create
    order = current_user.orders.find_or_create_by(
        status: false
      )

    @product = Product.find(params[:product_id])

    @order_product = OrderProduct.new
    @order_product.order = order
    @order_product.product = @product

    authorize @order_product

    if @order_product.save
      redirect_to products_path
    end
  end

  def destroy
    order_product = OrderProduct.find(params[:id])
    authorize order_product
    @product = order_product.product
    order_product.destroy
    redirect_to products_path

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def orders
    @orders = Order.all
    @products = Product.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  # THE 1ST PART ALLOWS US THAT WHEN SOMEONE BUY A PRODUCT, IN THE
  # INDEX HE ONLY HAS ACCESS TO THE ARTICLES FROM THE SAME SELLER

  def index
    if params[:search]
      @products = Product.product_search(params[:search])
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product

    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    authorize @product

    if @product.update(product_params)
      redirect_to product_path(@product.id)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product

    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :gender, :size, :brand, :category, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_price(price)
    "U$ #{price / 100.0}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plus Size Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render "shared/navbar"%>
    <%= yield %>
  </body>
  <%= render "shared/footer"%>
</html>

app/views/orders/index.html.erb
<h2>Here is your shopping cart</h2>

app/views/pages/home.html.erb
<body>
  <div class="banner">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="s"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="https://images.pexels.com/photos/3618732/pexels-photo-3618732.jpeg" alt="Slide 1">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.pexels.com/photos/3843442/pexels-photo-3843442.jpeg" alt="Slide 2">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.pexels.com/photos/3778934/pexels-photo-3778934.jpeg" alt="Slide 3">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.pexels.com/photos/4358441/pexels-photo-4358441.jpeg" alt="Slide 4">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="container mt-5 mb-5">
    <h3 class="text-center mt-5 p-5"><strong>DESIGNED FOR YOUR HAPPINESS</strong></h3>
    <div class="cards">
      <div class="card">
        <h5 class="m-4"><strong>BUY</strong></h5>
        <p class="p-2">Buy clothes from your favorite brands for a cheaper price.</p>
      </div>

      <div class="card">
        <h5 class="m-4"><strong>SELL</strong></h5>
        <p class="p-2">Sell clothes you don't want and make someone happy.</p>
      </div>

      <div class="card">
        <h5 class="m-4"><strong>FEEL GOOD</strong></h5>
        <p class="p-2">Feel confident with clothing that fit perfectly on you.</p>
      </div>
    </div>
    <div class="product-button">
      <a class="btn btn-dark" href="/products" role="button">All Products</a>
    </div>
  </div>
</body>

app/views/products/edit.html.erb
<h2>Edit Your Product</h2>

<%= simple_form_for(@product) do |form| %>
  <div class="contrainer pt-2">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6 col-lg-3">
        <h2 class="text-center mb-5 devise-padding">Sell your product!</h2>
        <div class="row">
          <div class="col">
            <div class="form-inputs">
              <div class="row">
                <div class="col">
                  <%= form.input :name %>
                  <%= form.input :description %>
                  <%= form.input :gender, collection: Product::GENDER %>
                  <%= form.input :size, collection: Product::SIZE %>
                  <%= form.input :brand %>
                  <%= form.input :category, collection: Product::CATEGORY %>
                  <%= form.input :photo, as: :file %>
                  <%= form.input :price %>
                  <div class="row">
                    <div class="col">
                      <%= form.submit "Updated", class: "btn-outline-dark btn-lg w-15 mt-3 button-center" %>
                    </div>
                    <div class="col">
                      <p><%= link_to "Back to product", products_path(@product.id) %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<!-- <p><%= link_to "Add A Product", new_product_path %></p> --> <%# Move to navbar if user authorized %>

<div class="card-deck">
  <% @products.each do |product| %>
  <div class="row card-img-top col-md-3" >
    <%= link_to product_path(product.id) do %>
      <img class="card-img-top"><%= cl_image_tag product.photo.key, height: 280, width: 280, crop: :fill, alt: product.name %>
        <%= "#{product.name}" %>
        <% if (current_user != product.user) && current_user.present? %>
          <% if product.is_it_in_the_shopping_cart?(current_user) %>
            <%= link_to "Remove from Cart", order_product_path(product.cart_product(current_user)), method: :delete, class: "btn btn-danger" %>
          <% else %>
            <%= link_to "Add to cart", order_products_path(product_id: product.id), method: :post, class: "btn btn-primary" %>
          <% end %>
        <% end %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%# The user can only add a new product if logged in - authorization + navbar %>

<%= simple_form_for(@product) do |form| %>
  <div class="contrainer">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6 col-lg-4">
        <h2 class="text-center mt-2 pb-5 devise-padding">SELL YOUR PRODUCT</h2>
        <div class="row">
          <div class="col">
            <div class="form-inputs">
              <div class="row">
                <div class="col">
                  <div class="pb-3">
                    <%= form.input :name, placeholder: "Black Dress in Silk"%>
                  </div>
                  <div class="pb-3">
                    <%= form.input :description, placeholder: "A perfect dress waiting for the perfect owner" %>
                  </div>
                  <div class="pb-3">
                    <%= form.input :gender, collection: Product::GENDER %>
                  </div>
                  <div class="pb-3">
                    <%= form.input :size, collection: Product::SIZE %>
                  </div>
                  <div class="pb-3">
                    <%= form.input :brand, placeholder: "Zara" %>
                  </div>
                  <div class="pb-3">
                    <%= form.input :category, collection: Product::CATEGORY %>
                  </div>
                  <div class="pb-3">
                    <%= form.input :photo, as: :file, placeholder: "Upload a picture" %>
                  </div>
                  <div class="pb-3">
                    <%= form.input :price %>
                  </div>
                  <div class="pb-5 mb-4">
                    <%= form.submit "Sell it", class: "btn btn-dark btn-block" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="container mt-5 mb-5">
  <div class="cards">
    <div class="product-card">
      <div class="product-title">
        <h2 class="mt-5 mb-3"><strong><%= @product.name.upcase %></strong></h2>
        <p>In <strong><%= @product.category.capitalize %></strong></p>
        <p><i><%= @product.description %></i></p>
      </div>
      <div class="product-info row justify-content-around">
        <div class="info mt-5 pt-5 mr-5 pr-5">
          <ul>
            <p><strong><%= "USD #{@product.price},00" %></strong></p>
            <p>Gender: <%= @product.gender.capitalize %></p>
            <p>Brand: <%= @product.brand.capitalize %></p>
            <p>Size: <%= @product.size %></p>
            <% if current_user.id == @product.user_id %>
              <p><%= link_to "Edit Product", edit_product_path, class: "btn btn-outline-dark" %></p>
              <p><%= link_to "Delete Product", product_path(@product.id), class: "btn btn-outline-dark", method: :delete, data: { confirm: "Delete #{@product.name}?" } %></p>
            <% else %>
              <p><%= link_to "Add to cart", order_products_path(product_id: @product.id), method: :post, class: "btn btn-dark" %></p>
            <% end %>
            <p><%= link_to "All Products", products_path, class: "btn btn-dark" %></p>
          </ul>
        </div>
        <div class="product-image ml-5 mt-5 pl-5 mr-5 pr-5">
          <p class="image"><%= cl_image_tag @product.photo.key, height: 500, width: 280, crop: :fill, alt: @product.name %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer pt-5">
  <footer class="page-footer font-small text-light bg-dark pt-3 pb-3">
    <div class="footer-copyright text-center py-3">© 2020 Copyright, All rights reserved.</div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="nav navbar-light bg-light justify-content-between pt-2 pb-2 pr-3 pl-3">
  <div class="nav-brand">
    <a class="navbar-brand pr-4" href="/"><strong>PLUS SIZE ME</strong></a>
  </div>

  <div class="nav-search">
    <form class="form-inline d-flex" action="/products" method="get">
      <input class="form-control" name="search" type="search" placeholder="Search" aria-label="Search">
      <button class="btn text-secondary" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>

  <div class="nav-menu d-flex">
    <% if current_user %>
      <a class="btn text-dark ml-2 mt-1" href="/orders" role="button"><i class="fas fa-shopping-cart"></i></a>
      <%= link_to "Add Product", new_product_path, class: "btn btn-dark ml-2" %>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <i class="fas fa-user-circle fa-lg avatar text-dark ml-3 mt-2 pt-1" data-toggle="dropdown"></i>
          <div class="dropdown-menu dropdown-menu-right">
            <p class="pl-3 pt-2"><%= "Hi, #{current_user.first_name}!" %></p>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn pl-3 pt-0", data: { confirm: "Are you sure you want to disconnect?" } %>
          </div>
        </li>
      </ul>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-outline-dark ml-2" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-dark ml-2" %>
    <% end %>
  </div>
</nav>